#!/bin/sh

# The url to download
url="$1"

# The file prefix
prefix="$2"

if [ "$#" = 2 ]; then
  suffix=''
elif [ "$#" = 3 ]; then
  suffix=".$3"
else
  echo "USAGE: $0 [url] [filename prefix] [extension (optional)]"
  exit 1
fi

# The file to save to
file="${prefix}-$(date --rfc-3339 ns)${suffix}"

# The symlink to the current version
link="${prefix}${suffix}"

wget -O "${file}" "${url}"

md5sum "${file}" > "${file}.md5"
md5a=$(cut -d \  -f 1 "${file}.md5")

if [ -h $link ]; then
  linkmd5=$(readlink "${link}.md5")
  md5b=$(cut -d \  -f 1 "${link}.md5")
fi

if [ -h $link ] && [ "$md5a" = "$md5b" ]; then
  # If this is the same as the previous file,
  # delete the current file
  rm "$file" "$file.md5"
else
  # If it's different or new, change the links
  rm -f "$link" "$link.md5"
  ln -s "$file" "$link"
  ln -s "$file.md5" "$link.md5"
fi
